const employees = [
  {
    id: 1,
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Update client report",
        description: "Finish and send Q1 report to client.",
        date: "2025-04-16",
        category: "Reporting",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Fix login bug",
        description: "Resolve the login error in mobile app.",
        date: "2025-04-12",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Prepare presentation",
        description: "Missed deadline for the internal presentation.",
        date: "2025-04-10",
        category: "Meetings",
      },
    ],
  },
  {
    id: 2,
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Design new UI",
        description: "Create wireframes for dashboard revamp.",
        date: "2025-04-16",
        category: "Design",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Code review",
        description: "Review pull requests for recent sprint.",
        date: "2025-04-15",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Sync meeting",
        description: "Daily stand-up with dev team.",
        date: "2025-04-14",
        category: "Meetings",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Client feedback",
        description: "Address issues raised by client on release v2.1.",
        date: "2025-04-13",
        category: "Support",
      },
    ],
  },
  {
    id: 3,
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Database migration",
        description: "Migrate legacy DB to PostgreSQL.",
        date: "2025-04-14",
        category: "Database",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "API docs update",
        description: "Update outdated endpoints in documentation.",
        date: "2025-04-13",
        category: "Documentation",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Team onboarding",
        description: "Onboard two new hires into the dev workflow.",
        date: "2025-04-16",
        category: "HR",
      },
    ],
  },
  {
    id: 4,
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Prepare training module",
        description: "Create technical onboarding materials.",
        date: "2025-04-16",
        category: "Training",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Security audit",
        description: "Perform internal audit of current services.",
        date: "2025-04-13",
        category: "Security",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Optimize API performance",
        description: "Reduce API response times by 20%.",
        date: "2025-04-12",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Customer support issue",
        description: "Failed to resolve critical client complaint.",
        date: "2025-04-11",
        category: "Support",
      },
    ],
  },
  {
    id: 5,
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Write blog post",
        description: "Publish article on recent feature updates.",
        date: "2025-04-16",
        category: "Marketing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "SEO audit",
        description: "Run SEO audit on main website.",
        date: "2025-04-14",
        category: "Marketing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Weekly newsletter",
        description: "Send out scheduled newsletter to subscribers.",
        date: "2025-04-13",
        category: "Marketing",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Landing page A/B test",
        description: "Test version B did not improve conversions.",
        date: "2025-04-12",
        category: "Marketing",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Market research",
        description: "Collect data on competitor campaigns.",
        date: "2025-04-16",
        category: "Research",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalstorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
};
export const getLocalstorage = () => {
  const data = localStorage.getItem("employees");
  console.log(data);
};
